#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinHud Configuration File:
#  Variables:
#   - {line} To Go To The Next Line
#   - {max_players} To Get The Max Players
#   - {online_players} To Get The Online Player Count
#   - & for color coding
#   - {x} to get the player's X position
#   - {y} to get the player's Y position
#   - {z} to get the player's Z position
#   - {level} To Get The Player's Level
#   - {tps} To Get The Ticks Per Second
#   - {motd} To Get The Message Of The Day

#  Default Config:
#    hud-message: "&bBlazinHud &bby &bBlazeTheDev {line} &b{online_players}&b/&b{max_players}"
#    multi-world: "true
#    worlds:
#     - "world"

# The below config is the hud message that will be displayed above your hotbar
hud-message: "&bBlazinHud &bby &bBlazeTheDev {line} &b{online_players}&b/&b{max_players}"

# The below config turns on or off multi-world support (NOTE: the 2 options here are on and off)
multi-world: "on"

# The below config is the world names that are supported for the hud (NOTE: If multi-world config is off then this will be useless)
worlds:
 - "world"
